all:	unity.o unity_fixture.o gui_test.o runall.o

gui_test.o:
	gcc -c gui_test.c -o ../build/gui_test.o

runall.o:
	gcc -c runall.c -o ../build/runall.o

unity.o:
	gcc -c ../../unity/unity.c -o ../build/unity.o

unity_fixture.o:
	gcc -c ../../unity/unity_fixture.c -o ../build/unity_fixture.o
