all: unity.o unity_fixture.o logic_test.o runall.o

logic_test.o:
	gcc -c logic_test.c -o ../build/logic_test.o

runall.o:
	gcc -c runall.c -o ../build/runall.o

unity.o:
	gcc -c ../../unity/unity.c -o ../build/unity.o

unity_fixture.o:
	gcc -c ../../unity/unity_fixture.c -o ../build/unity_fixture.o
